### PR TITLE
Add about page

### PR DESCRIPTION
**Pull request by Agbedeyisegun**
- Add about page
- Add link to home page for the about page.

### CODE REVIEW

**Review by Sulaimon-ade — COMMENTED** [review]
Good enough

**Review by Sulaimon-ade — APPROVED** [review]

**Review by Agbedeyisegun — COMMENTED** [review]
@stanleyogada @Sulaimon-ade pls check and review

**Review by stanleyogada — CHANGES_REQUESTED** [review]
Incomplete feature!!

Screenshot from 2023-12-14 16-46-29

**Add a link on the about page to return to the home page**

**Review by stanleyogada — APPROVED** [review]
LGTM ship it!

**Pull request merged**
